name: Sync with upstream Buildroot

on:
  schedule:
    - cron: '0 */5 * * *'  # alle 5 Stunden
  workflow_dispatch:

jobs:
  sync-upstream:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout own repo
        uses: actions/checkout@v4
        with:
          ref: master
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN }}

      - name: Set up Git config
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Add upstream and fetch
        run: |
          git remote add upstream https://github.com/buildroot/buildroot.git
          git fetch upstream

      - name: Merge upstream changes
        run: |
          git checkout master
          git merge upstream/master --ff-only || echo "No fast-forward possible"

      - name: Push changes if updated
        run: |
          git push origin master
